np.random.randn() 

np.random.randn() 함수는 NumPy의 난수 생성 함수 중 하나로, 표준 정규분포(평균 0, 분산 1)를 따르는 난수를 생성합니다. 이 함수는 위치 인자를 사용하여 출력 배열의 형태(shape)를 지정합니다.

표준 정규분포(평균 0, 분산 1)의 경우, 이론적으로 모든 실수값을 가질 수 있습니다. 즉, **범위는 
−∞부터 +∞**까지 입니다.

하지만 실제로는 확률 밀도가 다음과 같이 빠르게 감소하기 때문에 대부분의 값은 평균 근처에 집중됩니다.

약 **68%**의 값이 평균 ±1 표준편차 (즉, −1 ~ +1) 범위 내에 있습니다.
약 **95%**의 값이 평균 ±2 ±2 표준편차 (즉, −2 ~ +2) 범위 내에 있습니다.
약 **99.7%**의 값이 평균 ±3 표준편차 (즉, −3 ~ +3) 범위 내에 있습니다.
따라서, 대부분의 표준 정규분포 난수는 −3에서 +3 사이에 위치하지만, 이론적으로는 어떤 극단적인 값(매우 큰 음수나 양수)도 나타날 수 있습니다.

In [1]:
import numpy as np


In [2]:

#  단일 값 생성 (스칼라)
scalar_value = np.random.randn()
print("스칼라 난수:", scalar_value)


스칼라 난수: 0.23950473137401454


In [3]:
#  1차원 배열 생성 (크기 5)
array_1d = np.random.randn(5)
print("1차원 배열:", array_1d)

1차원 배열: [-2.72280267  0.07184426  0.04398008 -0.02334071 -0.44320471]


In [4]:
# 2차원 배열 생성 (3행 4열)
array_2d = np.random.randn(3, 4)
print("2차원 배열:\n", array_2d)

2차원 배열:
 [[-0.44235113  0.45489083  1.38144701 -0.05782655]
 [-1.11410604 -0.99746011 -0.46013882  0.47216141]
 [-0.31657983  1.65056793  0.35117515  1.90762403]]


np.random.randn()

np.random.randn()는 내부적으로 np.random.standard_normal(size=...)를 호출하는 방식으로 동작합니다.따라서 두 함수는 생성하는 난수의 분포가 동일하며, 단지 인자 전달 방식에 차이가 있습니다.

In [5]:
np.random.randn(3, 4)

array([[-0.37493571, -1.18040645,  0.60895413, -1.63532656],
       [ 1.16623352,  0.35464189,  0.05026455, -1.72383686],
       [ 0.06695702,  1.13647969,  0.38758189,  0.7267068 ]])

In [6]:
np.random.standard_normal(size=(3, 4))

array([[ 0.36313491,  0.5236349 ,  1.35367522,  0.83864082],
       [ 1.42500817,  0.93358285, -0.74536343,  0.230065  ],
       [ 0.8701432 , -0.26471118,  1.00112805, -0.08380802]])