np.random.randn() 

np.random.randn() 함수는 NumPy의 난수 생성 함수 중 하나로, 표준 정규분포(평균 0, 분산 1)를 따르는 난수를 생성합니다. 이 함수는 위치 인자를 사용하여 출력 배열의 형태(shape)를 지정합니다.

표준 정규분포(평균 0, 분산 1)의 경우, 이론적으로 모든 실수값을 가질 수 있습니다. 즉, **범위는 
−∞부터 +∞**까지 입니다.

하지만 실제로는 확률 밀도가 다음과 같이 빠르게 감소하기 때문에 대부분의 값은 평균 근처에 집중됩니다.

약 **68%**의 값이 평균 ±1 표준편차 (즉, −1 ~ +1) 범위 내에 있습니다.
약 **95%**의 값이 평균 ±2 ±2 표준편차 (즉, −2 ~ +2) 범위 내에 있습니다.
약 **99.7%**의 값이 평균 ±3 표준편차 (즉, −3 ~ +3) 범위 내에 있습니다.
따라서, 대부분의 표준 정규분포 난수는 −3에서 +3 사이에 위치하지만, 이론적으로는 어떤 극단적인 값(매우 큰 음수나 양수)도 나타날 수 있습니다.

In [2]:
import numpy as np


In [4]:

#  단일 값 생성 (스칼라)
scalar_value = np.random.randn()
print("스칼라 난수:", scalar_value)


스칼라 난수: -0.940503556651414


In [5]:
#  1차원 배열 생성 (크기 5)
array_1d = np.random.randn(5)
print("1차원 배열:", array_1d)

1차원 배열: [-1.96022109  0.04659818 -0.52634     0.58313517 -0.37390981]


In [6]:
# 2차원 배열 생성 (3행 4열)
array_2d = np.random.randn(3, 4)
print("2차원 배열:\n", array_2d)

2차원 배열:
 [[ 0.63007692  0.57815316 -1.2466273  -0.79660942]
 [ 0.20383489  0.52020052  0.84258251 -0.40846899]
 [-0.58425189 -2.08736619  0.12456809  0.64869907]]


np.random.randn()

np.random.randn()는 내부적으로 np.random.standard_normal(size=...)를 호출하는 방식으로 동작합니다.따라서 두 함수는 생성하는 난수의 분포가 동일하며, 단지 인자 전달 방식에 차이가 있습니다.

In [4]:
np.random.randn(3, 4)

array([[ 0.21125105, -0.78732254,  0.62214161,  1.08742242],
       [ 0.9578089 , -1.80362852, -1.00132741, -0.52543388],
       [-0.54399371, -0.58109332,  1.53870122, -0.19689198]])

In [5]:
np.random.standard_normal(size=(3, 4))

array([[-0.37219633,  0.60368599,  0.97303158,  1.18431239],
       [-1.07344199, -0.01330353,  0.25187265, -1.24445158],
       [ 1.65804946, -1.23906248,  1.38861477, -0.18503896]])