np.random.seed() 

np.random.seed() 함수는 NumPy의 난수 생성기(Random Number Generator, RNG)의 시드를 설정하는 역할을 합니다. 여기서 파라미터는 난수 생성의 초기 상태를 결정하는 정수값입니다.

시드를 설정하면 이후 생성되는 난수들이 동일한 순서로 나오게 되어, 동일한 코드를 실행할 때마다 같은 결과를 얻을 수 있습니다. 예를 들면 np.random.seed(42) 으로 seed를 42로 설정하면 코드가 실행되는 환경이나 시점에 상관없이 동일한 난수 배열을 생성할 수 있습니다.

In [1]:
import numpy as np

In [2]:
np.random.seed(42)
np.random.randn(3)


array([ 0.49671415, -0.1382643 ,  0.64768854])

In [3]:
np.random.seed(None)
np.random.randn(3)

array([-0.90402811, -1.06127571, -0.2178188 ])

In [4]:
np.random.seed(42)
np.random.randn(3)

array([ 0.49671415, -0.1382643 ,  0.64768854])