np.random.normal() 

np.random.normal() 함수는 지정된 평균과 표준편차를 갖는 정규분포(가우시안 분포)를 따르는 난수를 생성하는 함수입니다. 주요 파라미터들은 다음과 같습니다:

loc (float or array_like, default=0.0):

정규분포의 평균(μ) 값을 지정합니다.
단일 값이나 배열로 제공할 수 있으며, 각 난수가 이 평균을 중심으로 생성됩니다.
scale (float or array_like, default=1.0):

정규분포의 표준편차(σ) 를 지정합니다.
표준편차는 분포의 퍼짐 정도를 나타내며, 음수가 아닌 값이어야 합니다.
size (int or tuple of ints, optional):

생성할 난수 배열의 형태(shape) 를 지정합니다.
예를 들어, size=(3,4)로 설정하면 3행 4열의 배열을 반환합니다.
기본값은 None으로, 이 경우 단일 스칼라 값을 반환합니다.

In [3]:
import numpy as np

In [6]:
#평균 0, 표준편차 1의 단일 난수 생성
value = np.random.normal()
print("단일 난수:", value)

단일 난수: -0.6594996670325625


In [4]:
#평균 10, 표준편차 2의 단일 난수 생성
value = np.random.normal(loc=10, scale=2)
print("평균 10, 표준편차 2의 단일 난수:", value)

평균 10, 표준편차 2의 단일 난수: 11.77649862464947


In [12]:
# 평균 0, 표준편차 1의 1차원 배열 (크기 5) 생성
array_1d = np.random.normal(loc=0, scale=1, size=5)
print("1차원 배열:", array_1d)

1차원 배열: [-1.206648    2.22984264  0.41948077 -1.46742452  0.16955563]


In [7]:

# 평균 5, 표준편차 3의 2차원 배열 (3행 4열) 생성
array_2d = np.random.normal(loc=5, scale=3, size=(3, 4))
print("2차원 배열:\n", array_2d)


2차원 배열:
 [[ 4.74874772e+00  7.36886593e+00  4.99696318e+00  3.43835898e+00]
 [-9.75949860e-04  7.43168399e+00  2.99068970e+00  5.93688845e+00]
 [ 1.21086758e+01  1.18824623e+01  4.92356686e+00  9.55521380e+00]]
